{
  "hash": "760c1a5ffa01075810e8ba43096ceaec",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Predictive Policing - Technical Implementation\"\nsubtitle: \"Exploring Burglaries Patterns in Chicago and Predictive Modeling with 311 Data\"\nauthor: \"Yuqing(Demi) Yang\"\ndate: today\nformat:\n  html:\n    code-fold: show\n    code-tools: true\n    toc: true\n    toc-depth: 3\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\neditor: visual\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\nIn this lab, you will apply the spatial predictive modeling techniques demonstrated in the class exercise to a 311 service request type of your choice. You will build a complete spatial predictive model, document your process, and interpret your results.\n\n### Timeline & Deliverables\n\n**Due Date:** November 17, 2025, 10:00AM\n\n**Deliverable:** One rendered document, posted to your portfolio website.\n\n### Learning Goals\n\nBy completing this assignment, you will demonstrate your ability to:\n\n-   Adapt example code to analyze a new dataset\n-   Build spatial features for predictive modeling\n-   Apply count regression techniques to spatial data\n-   Implement spatial cross-validation\n-   Interpret and communicate model results\n-   Critically evaluate model performance\n\n------------------------------------------------------------------------\n\n# Step 0: Set Up\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(tidyverse)      # Data manipulation\nlibrary(sf)             # Spatial operations\nlibrary(here)           # Relative file paths\nlibrary(viridis)        # Color scales\nlibrary(terra)          # Raster operations (replaces 'raster')\nlibrary(spdep)          # Spatial dependence\nlibrary(FNN)            # Fast nearest neighbors\nlibrary(MASS)           # Negative binomial regression\nlibrary(patchwork)      # Plot composition (replaces grid/gridExtra)\nlibrary(knitr)          # Tables\nlibrary(kableExtra)     # Table formatting\nlibrary(classInt)       # Classification intervals\nlibrary(here)\n\n# Spatstat split into sub-packages\nlibrary(spatstat.geom)    # Spatial geometries\nlibrary(spatstat.explore) # Spatial exploration/KDE\n\n# Set options\noptions(scipen = 999)  # No scientific notation\nset.seed(5080)         # Reproducibility\n\n# Create consistent theme for visualizations\ntheme_default <- function(base_size = 11) {\n  theme_minimal(base_size = base_size) +\n    theme(\n      plot.title = element_text(face = \"bold\", size = base_size + 1),\n      plot.subtitle = element_text(color = \"gray30\", size = base_size - 1),\n      legend.position = \"right\",\n      panel.grid.minor = element_blank(),\n      axis.text = element_blank(),\n      axis.title = element_blank()\n    )\n}\n\n# Set as default\ntheme_set(theme_default())\n\ncat(\"✓ All packages loaded successfully!\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ All packages loaded successfully!\n```\n\n\n:::\n:::\n\n\n# Step 1: Getting the Data\n\n## 1.1 Load Chicago Spatial Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load police districts (used for spatial cross-validation)\npoliceDistricts <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(District = dist_num)\n\n# Load police beats (smaller administrative units)\npoliceBeats <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(Beat = beat_num)\n\n# Load Chicago boundary\nchicagoBoundary <- \n  st_read(\"https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson\") %>%\n  st_transform('ESRI:102271')\n\ncat(\"  - Police districts:\", nrow(policeDistricts), \"\\n\")\ncat(\"  - Police beats:\", nrow(policeBeats), \"\\n\")\n```\n:::\n\n\n## 1.2 Load 311 Rodent Baiting Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrb <- read_csv(\"data/311_Service_Requests_-_Rodent_Baiting_-_Historical_20251114.csv\")\nhead(rb)\n\nrb_sf <- rb %>%\n  filter(!is.na(Latitude), !is.na(Longitude)) %>% \n  st_as_sf(coords = c(\"Longitude\", \"Latitude\"), crs = 4326) %>% \n  st_transform(\"ESRI:102271\")  \n\nrb_sf <- rb_sf %>% \n  filter(st_within(., chicagoBoundary, sparse = FALSE))\n\n# filter 2017 data\nrb_sf$CreationDate <- as.Date(rb_sf$`Creation Date`, format = \"%m/%d/%Y\")\nrb_sf_2017 <- rb_sf %>% \n  filter(format(CreationDate, \"%Y\") == \"2017\")\n```\n:::\n\n\n## 1.3 Load Burglary Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load from provided data file (downloaded from Chicago open data portal)\nburglaries <- st_read(\"data/burglaries.shp\") %>% \n  st_transform('ESRI:102271')\n\n# Check the data\ncat(\"  - Number of burglaries:\", nrow(burglaries), \"\\n\")\ncat(\"  - CRS:\", st_crs(burglaries)$input, \"\\n\")\n```\n:::\n\n\n## 1.4 Visualize Point Data\n\n### 1.4.1 Rodent Baiting Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple point map for Rodent Baiting\np1 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = rb_sf_2017, color = \"#d62828\", size = 0.1, alpha = 0.4) +\n  labs(\n    title = \"Rodent Baiting 311 Service Requests\",\n    subtitle = paste0(\"Chicago, n = \", nrow(rb_sf_2017))\n  )\n\n# Density surface using 311 Rodent Baiting data\np2 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(rb_sf_2017)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel density estimation of Rodent Baiting Requests\"\n  )\n\n# Combine plots using patchwork\np1 + p2 + \n  plot_annotation(\n    title = \"Spatial Distribution of Rodent Baiting 311 Requests in Chicago\",\n    tag_levels = \"A\"\n  )\n```\n\n::: {.cell-output-display}\n![](Assignment4_SpatialPredictiveAnalysis_files/figure-html/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n-   The maps above show the spatial distribution of Rodent Baiting 311 requests across Chicago.\\\n-   The point map on the left illustrates the raw locations of all reported rodent issues. The large number of points makes the overall pattern dense, but we can still see clear clusters in the northern and western parts of the city.\\\n-   The density map on the right provides a smoother view of these patterns. Several strong hotspots emerge, especially in the Northwest Side and Near North areas. In contrast, the southern and far southwestern parts of Chicago show much lower intensity.\n\n### 1.4.2 Burgalaries Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple point map for Burglaries (P3)\np3 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = burglaries, color = \"#003f5c\", size = 0.15, alpha = 0.5) +\n  labs(\n    title = \"Residential Burglaries\",\n    subtitle = paste0(\"Chicago, n = \", nrow(burglaries))\n  )\n\n# Density surface for Burglaries (P4)\np4 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(burglaries)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel density estimation of Residential Burglaries\"\n  )\n\n# Combine P3 & P4\np3 + p4 +\n  plot_annotation(\n    title = \"Spatial Distribution of Residential Burglaries in Chicago\",\n    tag_levels = \"A\"\n  )\n```\n\n::: {.cell-output-display}\n![](Assignment4_SpatialPredictiveAnalysis_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n-   The maps show where residential burglaries were concentrated in Chicago.\n-   The darker purple areas represent the highest concentrations of burglaries. These hot spots appear mainly in the north and south-central parts of the city.\n-   Overall, the maps suggest that residential burglaries cluster in specific neighborhoods rather than occurring randomly across Chicago.\n\n## 1.5 Chapter Summary\n\n-   **Load maps and boundaries of Chicago:**\n    -   This chapter loads police districts, police beats, and the city boundary.\\\n    -   These layers help define the study area and later allow spatial analysis.\\\n    -   All maps are changed into the same coordinate system so they line up correctly.\n-   **Load 311 Rodent Baiting data:**\n    -   This chapter loads Chicago 311 Rodent Baiting data, and keeps only records from 2017.\n-   **Load burglary data:**\n    -   A shapefile of burglary cases is loaded.\\\n    -   It is also transformed into the same coordinate system.\\\n    -   This dataset will be compared with the rodent data later.\n-   **Purpose of Step 1:**\n    -   Gather most of the data needed for the project.\\\n    -   Clean and filter the data so it is accurate and consistent.\\\n    -   Make basic maps to understand where events happen.\n\n# Step 2: Fishnet Grid Creation\n\n## 2.1 Create Fishnet Grid\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create 500m x 500m grid\nfishnet <- st_make_grid(\n  chicagoBoundary,\n  cellsize = 500,  # 500 meters per cell\n  square = TRUE\n) %>%\n  st_sf() %>%\n  mutate(uniqueID = row_number())\n\n# Keep only cells that intersect Chicago\nfishnet <- fishnet[chicagoBoundary, ]\n\n# View basic info\ncat(\"  - Number of cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of cells: 2458 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell size:\", 500, \"x\", 500, \"meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell size: 500 x 500 meters\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell area:\", round(st_area(fishnet[1,])), \"square meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell area: 250000 square meters\n```\n\n\n:::\n:::\n\n\n## 2.2 Aggregate data to Grid\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join: which cell contains each rodent baiting request/burglaries?\n\nrodent_fishnet <- st_join(rb_sf_2017, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarise(countRodent = n(), .groups = \"drop\")\n\nburglary_fishnet <- st_join(burglaries, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarise(countBurglaries = n(), .groups = \"drop\")\n\n# Join back to fishnet (cells with 0 requests will be NA)\n\nfishnet <- fishnet %>%\n  left_join(rodent_fishnet,   by = \"uniqueID\") %>%\n  left_join(burglary_fishnet, by = \"uniqueID\") %>%\n  mutate(\n    countRodent     = tidyr::replace_na(countRodent, 0),\n    countBurglaries = tidyr::replace_na(countBurglaries, 0)\n  )\n```\n:::\n\n\n-   Summary statistics for Rodent baiting request\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(summary(fishnet$countRodent))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    2.00   11.00   20.68   30.00  180.00 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCells with zero rodent requests:\",\n    sum(fishnet$countRodent == 0), \"/\",\n    nrow(fishnet), \"(\",\n    round(100 * sum(fishnet$countRodent == 0) / nrow(fishnet), 1), \"% )\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCells with zero rodent requests: 500 / 2458 ( 20.3 % )\n```\n\n\n:::\n:::\n\n\n-   Summary statistics for Burglary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(summary(fishnet$countBurglaries))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   0.000   2.000   3.042   5.000  40.000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCells with zero burglaries:\",\n    sum(fishnet$countBurglaries == 0), \"/\",\n    nrow(fishnet), \"(\",\n    round(100 * sum(fishnet$countBurglaries == 0) / nrow(fishnet), 1), \"% )\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCells with zero burglaries: 781 / 2458 ( 31.8 % )\n```\n\n\n:::\n:::\n\n\n## 2.3 Visualize Rodent Baiting with fishnet\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = countRodent), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name   = \"Rodent Baiting Requests\",\n    option = \"plasma\",\n    trans  = \"sqrt\",\n    breaks = c(0, 5, 10, 20, 40, 80, 180),\n    limits = c(0, 180), \n    oob    = scales::squish\n  ) +\n  labs(\n    title = \"Rodent Baiting 311 Requests by Grid Cell\",\n    subtitle = \"500m x 500m cells, Chicago,2017\"\n  ) +\n  theme_default()\n```\n\n::: {.cell-output-display}\n![](Assignment4_SpatialPredictiveAnalysis_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\nquant_rb <- tibble(\n  Percentile = c(\"0%\", \"10%\", \"20%\", \"30%\", \"40%\", \"50%\", \"60%\", \"70%\", \"80%\", \"90%\", \"100%\"),\n  Value = quantile(fishnet$countRodent, probs = seq(0,1,0.1))\n)\n\nknitr::kable(\n  quant_rb,\n  caption = \"Quantile Distribution of Rodent Baiting 311 Request Counts\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Quantile Distribution of Rodent Baiting 311 Request Counts\n\n|Percentile | Value|\n|:----------|-----:|\n|0%         |     0|\n|10%        |     0|\n|20%        |     0|\n|30%        |     3|\n|40%        |     7|\n|50%        |    11|\n|60%        |    17|\n|70%        |    24|\n|80%        |    36|\n|90%        |    56|\n|100%       |   180|\n\n\n:::\n:::\n\n\n-   Most grid cells have very low request counts. According to the quantile table, 30% of the cells have 3 or fewer requests, and 50% have 11 or fewer.\\\n-   This pattern shows a strong **right-skewed distribution**, where a small number of hotspots generate many more requests than the rest of the city.\\\n-   On the map, hotspots appear mainly in the **central and north neighborhoods**, forming clear clusters of higher counts, and suggesting strong spatial heterogeneity.\n\n## 2.4 Visualize Burgalaries with fishnet\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Burglary 500m x 500m grid map\nggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name   = \"Residential Burglaries\",\n    option = \"plasma\",\n    trans  = \"sqrt\",\n    breaks = c(0, 1, 2, 3, 5, 8, 40),\n    limits = c(0, 40),\n    oob    = scales::squish\n  ) +\n  labs(\n    title = \"Residential Burglaries by Grid Cell\",\n    subtitle = \"500m x 500m cells, Chicago, 2017\"\n  ) +\n  theme_default()\n```\n\n::: {.cell-output-display}\n![](Assignment4_SpatialPredictiveAnalysis_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\nquant_burglary <- tibble(\n  Percentile = c(\"0%\", \"10%\", \"20%\", \"30%\", \"40%\", \"50%\", \"60%\", \"70%\", \"80%\", \"90%\", \"100%\"),\n  Value = quantile(fishnet$countBurglaries, probs = seq(0, 1, 0.1), na.rm = TRUE)\n)\n\nknitr::kable(\n  quant_burglary,\n  caption = \"Quantile Distribution of Residential Burglary Counts\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Quantile Distribution of Residential Burglary Counts\n\n|Percentile | Value|\n|:----------|-----:|\n|0%         |     0|\n|10%        |     0|\n|20%        |     0|\n|30%        |     0|\n|40%        |     1|\n|50%        |     2|\n|60%        |     3|\n|70%        |     4|\n|80%        |     5|\n|90%        |     8|\n|100%       |    40|\n\n\n:::\n:::\n\n\n-   Most grid cells have **very few burglaries**. From the quantiles, 50% of all cells have 2 or fewer burglary cases.\\\n-   The distribution is **right-skewed**. Many places have low values (0–3), while only a few places have high values.\\\n-   On the map, brighter colors (yellow) show where burglaries are concentrated. These hotspots appear mainly in the northern and southern parts of Chicago.\\\n-   The pattern suggests burglary risk is **not uniform** across the city. Instead, it clusters in specific neighborhoods, which is important for modeling and prediction.\n\n## 2.5 Chapter Summary\n\n-   **Creating the Fishnet Grid:**\n    -   This chapter created a 500m × 500m grid that covers the whole Chicago boundary.\\\n    -   Each grid cell gets a unique ID, which helps match spatial features later.\\\n    -   The grid makes it easier to compare different locations using the same unit of space.\n-   **Aggregating Rodent and Burglary Data:**\n    -   Each 311 rodent request and burglary point is assigned to a grid cell using a spatial join.\\\n    -   Then, this chapter counted how many events happen in each cell.\\\n    -   Cells with no events are filled with zero, so the dataset stays complete.\\\n    -   This step converts point data into count data, which is needed for statistical modeling.\n-   **Mapping Rodent Baiting Counts:**\n    -   The map shows clear hotspots where rodent activity is high.\\\n    -   The distribution is very skewed, meaning most cells have low values, but a few cells have extremely high values.\\\n    -   This pattern suggests strong spatial clustering.\n-   **Mapping Burglary Counts:**\n    -   Burglary counts also show uneven spatial distribution.\\\n    -   Many cells have 0–3 burglaries, while only a small number of cells have high counts.\\\n    -   This map confirms that burglaries are not random but cluster in specific neighborhoods.\n-   **Overall Importance of Step 2:**\n    -   This chapter transforms raw point data into a structured spatial dataset.\n    -   It creates the base layer (the grid) where all future variables will be attached.\n    -   It also reveals important spatial patterns that guide later modeling steps.\n\n# Step 3: Spatial Features\n\n## 3.1 k-nearest neighbor\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Get centroid coordinates\nfishnet_coords <- st_coordinates(st_centroid(fishnet))\n\n# 2. Compute nearest 8 neighbors (to other grid cells)\nknn_result <- get.knn(fishnet_coords, k = 8)\n\n# 3. Add KNN features to fishnet\nfishnet <- fishnet %>%\n  mutate(\n    knn_mean = rowMeans(matrix(countRodent[knn_result$nn.index], nrow = nrow(fishnet))),\n    knn_sum  = rowSums(matrix(countRodent[knn_result$nn.index],  nrow = nrow(fishnet)))\n  )\n\nsummary(fishnet$knn_mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   6.281  15.562  20.992  31.500 112.125 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$knn_sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00   50.25  124.50  167.94  252.00  897.00 \n```\n\n\n:::\n:::\n\n\n-   I calculated the **summary and mean values of neighboring grid cells** instead of the distance nearest event points. This method captures spatial spillover between neighborhoods better, providing stronger and more reliable predictive power.\n\n## 3.2 Distance to Hot Spots\n\n### 3.2.1 Perform Local Moran's I analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to calculate Local Moran's I\ncalculate_local_morans <- function(data, variable, k = 5) {\n  \n  # Create spatial weights based on k-nearest neighbors\n  coords <- st_coordinates(st_centroid(data))\n  neighbors <- knn2nb(knearneigh(coords, k = k))\n  weights <- nb2listw(neighbors, style = \"W\", zero.policy = TRUE)\n  \n  # Calculate Local Moran's I\n  local_moran <- localmoran(data[[variable]], weights)\n  \n  # Classify clusters\n  mean_val <- mean(data[[variable]], na.rm = TRUE)\n  \n  data %>%\n    mutate(\n      local_i = local_moran[, 1],\n      p_value = local_moran[, 5],\n      is_significant = p_value < 0.05,\n      \n      moran_class = case_when(\n        !is_significant ~ \"Not Significant\",\n        local_i > 0 & .data[[variable]] > mean_val ~ \"High-High\",\n        local_i > 0 & .data[[variable]] <= mean_val ~ \"Low-Low\",\n        local_i < 0 & .data[[variable]] > mean_val ~ \"High-Low\",\n        local_i < 0 & .data[[variable]] <= mean_val ~ \"Low-High\",\n        TRUE ~ \"Not Significant\"\n      )\n    )\n}\n\n# Apply to rodent baiting counts\nfishnet <- calculate_local_morans(fishnet, \"countRodent\", k = 5)\n```\n:::\n\n\n### 3.2.2 Visualize Morans\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| fig-width: 8\n#| fig-height: 6\n\n# Visualize Local Moran's I clusters for rodent baiting\nggplot() +\n  geom_sf(\n    data = fishnet, \n    aes(fill = moran_class), \n    color = NA\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"High-High\"       = \"#d7191c\",  # hotspots\n      \"High-Low\"        = \"#fdae61\",\n      \"Low-High\"        = \"#abd9e9\",\n      \"Low-Low\"         = \"#2c7bb6\",  # cold spots\n      \"Not Significant\" = \"gray90\"\n    ),\n    name = \"Cluster Type\"\n  ) +\n  labs(\n    title = \"Local Moran's I: Rodent Baiting Clusters\",\n    subtitle = \"High-High = Hot spots of rodent activity\"\n  ) +\n  theme_default()\n```\n\n::: {.cell-output-display}\n![](Assignment4_SpatialPredictiveAnalysis_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n-   **Why there is no \"Low-Low\" and \"High-Low\" clusters?**\n    -   The data shows a highly right-skewed distribution.\\\n    -   When high-value areas are clustered together, they are very likely to be identified as High-High (hotspot).\\\n    -   Low-value areas are everywhere, so \"low + low + low\" is too \"normal\" for the tests. As a result, it will not be marked as significantly \"Low-Low\", but rather \"Not Significant\".\n    -   In the reality, rodent activity is concentrated in a small number of hotspots, while low counts are widespread across the city.\n\n### 3.2.3 Distance to Hotspots\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get centroids of \"High-High\" cells (rodent hotspots)\nhotspots <- fishnet %>%\n  filter(moran_class == \"High-High\") %>%\n  st_centroid()\n\n# Calculate distance from each cell to nearest rodent hotspot\nif (nrow(hotspots) > 0) {\n  fishnet <- fishnet %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(st_centroid(fishnet), hotspots %>% st_union())\n      )\n    )\n  \n\n  cat(\"  - Number of hot spot cells:\", nrow(hotspots), \"\\n\")\n} else {\n  fishnet <- fishnet %>%\n    mutate(dist_to_hotspot = 0)\n  cat(\"⚠ No significant rodent baiting hot spots found\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of hot spot cells: 304 \n```\n\n\n:::\n:::\n\n\n## 3.3 Building Age\n\n### 3.3.1 Building Age Feature\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read building data\n\nbuilding_sf <- st_read(\"data/Building_Footprints_20251117.geojson\") %>%\n  \n# buildings_sf <- st_read(\n#   \"https://data.cityofchicago.org/resource/syp8-uezg.geojson\",\n#  quiet = TRUE\n# ) %>%\n\n\n# Clean and calculate the building years of 2017\n filter(!is.na(year_built)) %>%\n  mutate(year_built = as.numeric(year_built)) %>%\n  filter(year_built > 0, year_built <= 2017) %>%\n  mutate(bldg_age_2017 = 2017 - year_built) %>%\n  st_transform('ESRI:102271')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Building_Footprints_20251117' from data source \n  `/Users/demiyang/Downloads/MUSA/PPA/portfolio/portfolio-setup-demiyang12/assignments/assignment_4/data/Building_Footprints_20251117.geojson' \n  using driver `GeoJSON'\nreplacing null geometries with empty geometries\nSimple feature collection with 820606 features and 46 fields (with 6 geometries empty)\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.93981 ymin: 41.6446 xmax: -87.52421 ymax: 42.023\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nbldg_by_grid <- st_join(fishnet, building_sf, join = st_intersects) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(\n    n_buildings     = sum(!is.na(bldg_age_2017)),\n    mean_bldg_age   = ifelse(\n      n_buildings == 0, NA_real_,\n      mean(bldg_age_2017, na.rm = TRUE)\n    ),\n    median_bldg_age = ifelse(\n      n_buildings == 0, NA_real_,\n      median(bldg_age_2017, na.rm = TRUE)\n    ),\n    .groups = \"drop\"\n  )\n\nfishnet <- fishnet %>%\n  left_join(bldg_by_grid, by = \"uniqueID\")\n```\n:::\n\n\n### 3.3.2 Visualize Building Age\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = mean_bldg_age), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name   = \"Mean building age (years)\",\n    option = \"magma\",\n    direction = -1 ,\n    na.value = \"grey90\"\n  ) +\n  labs(\n    title    = \"Average Building Age by Grid Cell\",\n    subtitle = \"500m x 500m cells, Chicago, 2017\"\n  ) +\n  theme_default()\n```\n\n::: {.cell-output-display}\n![](Assignment4_SpatialPredictiveAnalysis_files/figure-html/unnamed-chunk-18-1.png){width=768}\n:::\n:::\n\n\n-   The map shows large differences in building age across Chicago.\\\n-   Newer buildings appear more often in the **central and far north** areas, where the colors are lighter.\\\n-   The pattern suggests that building age is not evenly distributed.Older structures cluster in certain neighborhoods, while others have more recent development.\\\n-   Many **burglary hotspots** appear in areas where **buildings are older**.\n    -   These locations, mainly in the north, and southeast parts of Chicago—show both high burglary counts and high building age.\\\n    -   Older buildings may have weaker physical security, such as outdated doors, windows, or locks.\\\n    -   Older neighborhoods may also have denser housing, which increases opportunities for burglary.\n\n## 3.4 Land Use\n\n### 3.4.1 Land Use Feature\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read the zoning data\n\n# zoning_sf <- st_read(\n#  \"https://data.cityofchicago.org/resource/dj47-wfun.geojson\",\n#  quiet = TRUE\n# )\n\nzoning_sf <- st_read(\"data/Boundaries_-_Zoning_Districts_(current)_20251117.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Boundaries_-_Zoning_Districts_(current)_20251117' from data source `/Users/demiyang/Downloads/MUSA/PPA/portfolio/portfolio-setup-demiyang12/assignments/assignment_4/data/Boundaries_-_Zoning_Districts_(current)_20251117.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 14814 features and 28 fields (with 4 geometries empty)\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94009 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Extract the letter parts of the first three characters from ZONE_CLASS\nzoning_sf <- zoning_sf %>%\n  mutate(\n    zone_prefix = substr(zone_class, 1, 3),\n    zone_prefix = gsub(\"[^A-Za-z]\", \"\", zone_prefix)\n  ) %>%\n  filter(zone_prefix != \"\") %>%\n  mutate(\n    zone_code = dplyr::recode(\n      zone_prefix,\n      \"RS\"  = \"1\",\n      \"RT\"  = \"2\",\n      \"RM\"  = \"3\",\n      \"B\"   = \"4\",\n      \"C\"   = \"5\",\n      \"DC\"  = \"6\",\n      \"DR\"  = \"7\",\n      \"DS\"  = \"8\",\n      \"DX\"  = \"9\",\n      \"M\"   = \"10\",\n      \"PMD\" = \"11\",\n      \"PD\"  = \"12\",\n      \"T\"   = \"13\",\n      \"POS\" = \"14\",\n      .default = NA_character_\n    )\n  ) %>%\n  filter(!is.na(zone_code)) %>%\n  \n  st_transform(\"ESRI:102271\")\n\nzoning_sf$zone_code <- as.integer(zoning_sf$zone_code)\n\n# Calculate the mode\nmode_first <- function(x) {\n  x <- x[!is.na(x)]\n  if (length(x) == 0) return(NA)\n  ux <- unique(x)\n  ux[which.max(tabulate(match(x, ux)))]\n}\n\n# Aggregate to fishnet: One zoning type for each grid\nzoning_by_grid <- st_join(fishnet, zoning_sf, join = st_intersects) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(\n    zone_prefix_dom = mode_first(zone_prefix), \n    zone_code_dom   = mode_first(zone_code),\n    .groups = \"drop\"\n  )\n\n# join the zoning variable back to fishnet\nfishnet <- fishnet %>%\n  left_join(zoning_by_grid, by = \"uniqueID\")\n```\n:::\n\n\n### 3.4.2 Visualize Land Use\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a zoning classification with complete instructions\nfishnet <- fishnet %>%\n  mutate(\n    zone_cat = factor(\n      zone_prefix_dom,\n      levels = c(\"RS\", \"RT\", \"RM\", \"B\",  \"C\",  \"DC\", \"DR\", \"DS\", \"DX\",\n                 \"M\",  \"PMD\", \"PD\", \"T\", \"POS\"),\n      labels = c(\n        \"RS = Residential Single-Unit District\",\n        \"RT = Residential Two-Flat, Townhouse and Multi-Unit District\",\n        \"RM = Residential Multi-Unit District\",\n        \"B = Business\",\n        \"C = Commercial\",\n        \"DC = Downtown Core District\",\n        \"DR = Downtown Residential District\",\n        \"DS = Downtown Service District\",\n        \"DX = Downtown Mixed-Use District\",\n        \"M = Manufacturing\",\n        \"PMD = Planned Manufacturing Districts\",\n        \"PD = Planned Development\",\n        \"T = Transportation\",\n        \"POS = Parks and Open Space\"\n      )\n    )\n  )\n\n#| fig-width: 8\n#| fig-height: 6\n\nggplot() +\n  geom_sf(data = fishnet, aes(fill = zone_cat), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_d(\n    name   = \"Zoning (dominant class)\",\n    option = \"turbo\", \n    na.value = \"grey90\"\n  ) +\n  labs(\n    title    = \"Dominant Zoning Category by Grid Cell\",\n    subtitle = \"500m x 500m cells, Chicago\"\n  ) +\n  theme_default() +\n  theme(\n    legend.key.height = unit(0.6, \"cm\"),\n    legend.key.width  = unit(0.6, \"cm\")\n  )\n```\n\n::: {.cell-output-display}\n![](Assignment4_SpatialPredictiveAnalysis_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n-   The map shows the dominant zoning type in each 500m × 500m grid cell in Chicago.\\\n-   The map shows Chicago has a mixed pattern, but **residential zones** dominate most of the city.\\\n-   Downtown districts (DR, DS, DX) are concentrated in the central east area.\\\n-   Manufacturing (M, PMD) zones cluster in the southeast, and middlewest.\\\n-   Comparing with burglary distribution, burglary hotspots occur mostly in **residential zones**.\n    -   This makes sense because burglary is a residential crime, so it appears mainly where people live.\\\n-   **Manufacturing zones** have low burglary counts.\n    -   These areas have fewer homes, more industrial facilities, and lower residential density.\n\n## 3.5 Chapter Summary\n\n-   **k-Nearest Neighbor (KNN) Feature for 311 request feature:**\n    -   For every cell, this chapter found its 8 nearest neighboring cells.\\\n    -   Then this chapter calculated `knn_mean`, which is the average rodent request count in those neighbors, and `knn_sum`, which is the total rodent request count in those neighbors.\n-   **Distance to Hot Spots Feature(Local Moran’s I):**\n    -   Each grid cell was classified into: `High–High (hotspot)`, `Low–Low`, `High–Low`, `Low–High`, or Not Significant. In practice, most significant clusters are High–High hotspots, while many low-count areas are “Not Significant” instead of Low–Low.\\\n    -   Then this chapter took the centroids of High–High cells and measured, for every grid cell, the distance to the nearest hotspot (`dist_to_hotspot`).\\\n    -   This creates a feature that shows how close each place is to intense rodent activity.\n-   **Building Age Feature:**\n    -   Building data was loaded from `Chicago Data Portal`, named `Building Footprints`.\\\n    -   This chapter cleaned the data and kept only buildings built before or in 2017, then computed building age in 2017.\n    -   Then, for each grid cell, this chapter calculated: `n_buildings`,which is this number of buildings with valid age. `mean_bldg_age`, which is the average building age. `median_bldg_age`, which is the median building age.\\\n    -   These values were joined back to the fishnet, so every cell has information about its building stock and age structure.\n-   **Land Use Feature:**\n    -   Zoning data was loaded from `Chicago Data Portal`, named `Boundaries - Zoning Districts (current)`.\\\n    -   This chapter aggregated the zoning data into the secondary classification of zoning classes.(reference: *https://secondcityzoning.org/zones/*)\\\n    -   For each cell, this chapter identified its function as its dominant zoning type.\\\n    -   A map of these categories shows how residential, commercial, downtown, industrial, and park areas are distributed across Chicago.\n-   **Purpose of Step 3:**\n    -   Step 3 builds key spatial predictor variables on top of the grid: neighborhood intensity (`knn_mean`), proximity to rodent hotspots (`dist_to_hotspot`), built environment age (`mean_bldg_age`), and land use type (`zone_code_dom`).\\\n    -   They are later used in the Poisson and Negative Binomial regression models as main explanatory variables.\n\n# Step 4: Count Regression Models\n\n## 4.1 Poisson regression\n\n### 4.1.1 Fit Poisson regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| label: poisson-reg\n#| message: false\n#| warning: false\n#| results: hide\n\nfishnet$zone_code_dom <- as.factor(fishnet$zone_code_dom)\n\npois_model <- glm(\n  countBurglaries ~ mean_bldg_age + zone_prefix_dom + dist_to_hotspot + knn_mean,\n  data = fishnet,\n  family = \"poisson\"\n)\n\nsummary(pois_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = countBurglaries ~ mean_bldg_age + zone_prefix_dom + \n    dist_to_hotspot + knn_mean, family = \"poisson\", data = fishnet)\n\nCoefficients:\n                        Estimate    Std. Error z value             Pr(>|z|)    \n(Intercept)         -0.250648101   0.072331678  -3.465              0.00053 ***\nmean_bldg_age        0.018883092   0.000700108  26.972 < 0.0000000000000002 ***\nzone_prefix_domC    -0.082138237   0.045501808  -1.805              0.07105 .  \nzone_prefix_domDR  -13.675893085 196.752921310  -0.070              0.94459    \nzone_prefix_domDS  -13.019003189 199.994386084  -0.065              0.94810    \nzone_prefix_domDX    0.185584582   0.197946901   0.938              0.34848    \nzone_prefix_domM    -0.783250148   0.063368112 -12.360 < 0.0000000000000002 ***\nzone_prefix_domPD   -0.215354060   0.053979269  -3.990        0.00006619324 ***\nzone_prefix_domPMD  -0.811643665   0.138020572  -5.881        0.00000000409 ***\nzone_prefix_domPOS  -0.262883964   0.088536272  -2.969              0.00299 ** \nzone_prefix_domRM    0.158877527   0.052655101   3.017              0.00255 ** \nzone_prefix_domRS   -0.167196608   0.031819723  -5.254        0.00000014843 ***\nzone_prefix_domRT   -0.027109217   0.040373445  -0.671              0.50193    \nzone_prefix_domT    -0.577170309   0.500635901  -1.153              0.24896    \ndist_to_hotspot     -0.000010614   0.000005785  -1.835              0.06658 .  \nknn_mean             0.002078690   0.000811532   2.561              0.01042 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 8415.3  on 2199  degrees of freedom\nResidual deviance: 6650.8  on 2184  degrees of freedom\n  (258 observations deleted due to missingness)\nAIC: 11849\n\nNumber of Fisher Scoring iterations: 10\n```\n\n\n:::\n:::\n\n\n### 4.1.2 Check for Overdispersion\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| label: poisson-dispersion-check\n#| message: false\n#| warning: false\n\ndispersion_rb <- sum(residuals(pois_model, type = \"pearson\")^2) /\n                 pois_model$df.residual\n\ncat(\"Dispersion parameter for rodent baiting Poisson model:\",\n    round(dispersion_rb, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDispersion parameter for rodent baiting Poisson model: 3.47 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Rule of thumb: values > 1.5 indicate overdispersion.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRule of thumb: values > 1.5 indicate overdispersion.\n```\n\n\n:::\n\n```{.r .cell-code}\nif (dispersion_rb > 1.5) {\n  cat(\"⚠ Overdispersion detected for rodent baiting counts.\\n\")\n  cat(\"  The Poisson model is likely too restrictive.\\n\")\n  cat(\"  A Negative Binomial model is more appropriate.\\n\")\n} else {\n  cat(\"✓ Dispersion looks acceptable.\\n\")\n  cat(\"  The Poisson model may be adequate for these counts.\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n⚠ Overdispersion detected for rodent baiting counts.\n  The Poisson model is likely too restrictive.\n  A Negative Binomial model is more appropriate.\n```\n\n\n:::\n:::\n\n\n## 4.2 Fit Negative Binomial regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnb_model <- glm.nb(\n  countBurglaries ~ mean_bldg_age + zone_prefix_dom + dist_to_hotspot + knn_mean,\n  data = fishnet\n)\n\nsummary(nb_model)\n```\n:::\n\n\n## 4.3 Compare model fit (AIC)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_compare <- data.frame(\n  Model = c(\"Poisson\", \"Negative Binomial\"),\n  AIC   = c(AIC(pois_model), AIC(nb_model))\n)\n\n\nknitr::kable(model_compare, caption = \"Model Comparison: Poisson vs. NB\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Model Comparison: Poisson vs. NB\n\n|Model             |       AIC|\n|:-----------------|---------:|\n|Poisson           | 11848.599|\n|Negative Binomial |  9836.521|\n\n\n:::\n\n```{.r .cell-code}\ndispersion_row <- data.frame(\n  Statistic = \"Poisson Dispersion\",\n  Value     = dispersion_rb\n)\n\nknitr::kable(dispersion_row, caption = \"Poisson Dispersion Statistic\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Poisson Dispersion Statistic\n\n|Statistic          |    Value|\n|:------------------|--------:|\n|Poisson Dispersion | 3.474401|\n\n\n:::\n:::\n\n\n## 4.4 Chapter Summary\n\n-   In this chapter, I built statistical models to explain how burglary counts change with spatial features:\\\n    building age, zoning, distance to rodent baiting counts hotspots, and mean values of rodent baiting counts in neighboring grid cells.\\\n-   Then, this chapter first fitted a Poisson regression with these variables and then checked the dispersion of the residuals. The **Poisson dispersion is about 3.47**, which is much larger than 1.5. This means the data are strongly overdispersed (variance much higher than the mean), so the Poisson model is too restrictive.\\\n-   To handle overdispersion, research then fitted a Negative Binomial (NB) regression with the same main predictors.This model allows **extra variance** and is better suited for these burglary counts.\\\n-   Poisson model has an **AIC of about 11849**, while the Negative Binomial model has an **AIC of about 9837**. A lower AIC means a better fit, so the **Negative Binomial model** performs much better.\\\n-   Overall, Step 4 shows that burglary counts are **highly overdispersed**, and that the Negative Binomial regression is the appropriate model for capturing the relationship between burglaries and the spatial features created in previous steps.\n\n# Step 5: Spatial Cross-Validation\n\n## 5.1 Leave-One-Group-Out cross-validation on 2017 data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate which police district the centroid of the grid falls in\nfishnet_centroids <- st_centroid(fishnet) %>%\n  st_join(policeDistricts, join = st_within) %>%\n  st_drop_geometry() %>%\n  dplyr::select(uniqueID, District)\n\n# Construct a dataset for cross-validation\nfishnet_model <- fishnet %>%\n  left_join(fishnet_centroids, by = \"uniqueID\") %>%\n  filter(!is.na(District)) %>%\n  mutate(\n    District      = as.factor(District),\n    zone_code_dom = as.factor(zone_code_dom)\n  ) %>%\n  filter(\n    !is.na(countRodent),\n    !is.na(mean_bldg_age),\n    !is.na(zone_code_dom),\n    !is.na(knn_mean),\n    !is.na(dist_to_hotspot)\n  )\n\n# LOGO CV\ndistricts  <- unique(fishnet_model$District)\ncv_results <- tibble()\n\nfor (i in seq_along(districts)) {\n  \n  test_district <- districts[i]\n  \n  # Divide the training set/test set\n  train_data <- fishnet_model %>% filter(District != test_district)\n  test_data  <- fishnet_model %>% filter(District == test_district)\n  \n  train_data <- train_data %>%\n    mutate(zone_code_dom = factor(zone_code_dom))\n  \n  test_data <- test_data %>%\n    mutate(zone_code_dom = factor(zone_code_dom,\n           levels = levels(train_data$zone_code_dom)))\n  \n  # Fit the NB model\nmodel_cv <- MASS::glm.nb(\n    countBurglaries ~ mean_bldg_age + zone_code_dom + dist_to_hotspot + knn_mean,\n    data = train_data\n  )\n  \n  # Make predictions on the test police district\n test_data <- test_data %>%\n    mutate(\n      prediction = predict(model_cv, newdata = ., type = \"response\"),\n      abs_error  = abs(countRodent - prediction),\n      sq_error   = (countRodent - prediction)^2\n    )\n \n   test_eval <- test_data %>% filter(!is.na(prediction))\n  \n mae  <- mean(test_eval$abs_error, na.rm = TRUE)\n rmse <- sqrt(mean(test_eval$sq_error, na.rm = TRUE))\n  \n  # Save the result\ncv_results <- bind_rows(\n    cv_results,\n    tibble(\n      fold          = i,\n      test_district = as.character(test_district),\n      n_test        = nrow(test_eval),\n      mae           = mae,\n      rmse          = rmse\n    )\n  )\n  \ncat(\"  Fold\", i, \"/\", length(districts),\n      \"- District\", as.character(test_district),\n      \"- n_test:\", nrow(test_eval),\n      \"- MAE:\", round(mae, 2),\n      \"- RMSE:\", round(rmse, 2), \"\\n\")\n}\n```\n:::\n\n\n## 5.2 Calculate and report error metrics (MAE, RMSE)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncv_sorted <- cv_results %>%\n  arrange(fold)\n\n# Table 1: local MAE and RMSE\ncv_sorted %>%\n  knitr::kable(\n    digits  = 2,\n    caption = \"Leave-One-District-Out CV Results (per district)\"\n  ) %>%\n  kableExtra::kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Leave-One-District-Out CV Results (per district)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> fold </th>\n   <th style=\"text-align:left;\"> test_district </th>\n   <th style=\"text-align:right;\"> n_test </th>\n   <th style=\"text-align:right;\"> mae </th>\n   <th style=\"text-align:right;\"> rmse </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:right;\"> 98 </td>\n   <td style=\"text-align:right;\"> 6.54 </td>\n   <td style=\"text-align:right;\"> 8.97 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:right;\"> 181 </td>\n   <td style=\"text-align:right;\"> 5.09 </td>\n   <td style=\"text-align:right;\"> 7.81 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:left;\"> 22 </td>\n   <td style=\"text-align:right;\"> 128 </td>\n   <td style=\"text-align:right;\"> 7.86 </td>\n   <td style=\"text-align:right;\"> 10.58 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:left;\"> 31 </td>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:right;\"> 1.79 </td>\n   <td style=\"text-align:right;\"> 2.17 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:right;\"> 81 </td>\n   <td style=\"text-align:right;\"> 15.27 </td>\n   <td style=\"text-align:right;\"> 21.39 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:left;\"> 8 </td>\n   <td style=\"text-align:right;\"> 227 </td>\n   <td style=\"text-align:right;\"> 23.52 </td>\n   <td style=\"text-align:right;\"> 35.95 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:left;\"> 7 </td>\n   <td style=\"text-align:right;\"> 67 </td>\n   <td style=\"text-align:right;\"> 25.62 </td>\n   <td style=\"text-align:right;\"> 31.88 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 8 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:right;\"> 59 </td>\n   <td style=\"text-align:right;\"> 8.14 </td>\n   <td style=\"text-align:right;\"> 10.87 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 9 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:right;\"> 78 </td>\n   <td style=\"text-align:right;\"> 7.88 </td>\n   <td style=\"text-align:right;\"> 12.69 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:left;\"> 9 </td>\n   <td style=\"text-align:right;\"> 140 </td>\n   <td style=\"text-align:right;\"> 18.20 </td>\n   <td style=\"text-align:right;\"> 28.11 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:left;\"> 10 </td>\n   <td style=\"text-align:right;\"> 84 </td>\n   <td style=\"text-align:right;\"> 22.02 </td>\n   <td style=\"text-align:right;\"> 32.60 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 12 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:right;\"> 44 </td>\n   <td style=\"text-align:right;\"> 6.66 </td>\n   <td style=\"text-align:right;\"> 10.72 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 13 </td>\n   <td style=\"text-align:left;\"> 12 </td>\n   <td style=\"text-align:right;\"> 98 </td>\n   <td style=\"text-align:right;\"> 21.82 </td>\n   <td style=\"text-align:right;\"> 35.64 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 14 </td>\n   <td style=\"text-align:left;\"> 15 </td>\n   <td style=\"text-align:right;\"> 37 </td>\n   <td style=\"text-align:right;\"> 19.80 </td>\n   <td style=\"text-align:right;\"> 25.29 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 15 </td>\n   <td style=\"text-align:left;\"> 11 </td>\n   <td style=\"text-align:right;\"> 65 </td>\n   <td style=\"text-align:right;\"> 23.88 </td>\n   <td style=\"text-align:right;\"> 31.78 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 16 </td>\n   <td style=\"text-align:left;\"> 18 </td>\n   <td style=\"text-align:right;\"> 43 </td>\n   <td style=\"text-align:right;\"> 29.25 </td>\n   <td style=\"text-align:right;\"> 40.30 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:left;\"> 25 </td>\n   <td style=\"text-align:right;\"> 113 </td>\n   <td style=\"text-align:right;\"> 28.05 </td>\n   <td style=\"text-align:right;\"> 36.95 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:left;\"> 14 </td>\n   <td style=\"text-align:right;\"> 65 </td>\n   <td style=\"text-align:right;\"> 45.98 </td>\n   <td style=\"text-align:right;\"> 57.32 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:left;\"> 19 </td>\n   <td style=\"text-align:right;\"> 89 </td>\n   <td style=\"text-align:right;\"> 43.28 </td>\n   <td style=\"text-align:right;\"> 56.53 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:left;\"> 16 </td>\n   <td style=\"text-align:right;\"> 179 </td>\n   <td style=\"text-align:right;\"> 16.79 </td>\n   <td style=\"text-align:right;\"> 23.99 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 21 </td>\n   <td style=\"text-align:left;\"> 17 </td>\n   <td style=\"text-align:right;\"> 97 </td>\n   <td style=\"text-align:right;\"> 37.12 </td>\n   <td style=\"text-align:right;\"> 47.60 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 22 </td>\n   <td style=\"text-align:left;\"> 20 </td>\n   <td style=\"text-align:right;\"> 45 </td>\n   <td style=\"text-align:right;\"> 41.37 </td>\n   <td style=\"text-align:right;\"> 51.85 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 23 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:right;\"> 54 </td>\n   <td style=\"text-align:right;\"> 55.43 </td>\n   <td style=\"text-align:right;\"> 63.31 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\n# Table 2: Average MAE and RMSe\ncv_summary <- cv_sorted %>%\n  summarise(\n    mean_MAE  = mean(mae,  na.rm = TRUE),\n    mean_RMSE = mean(rmse, na.rm = TRUE),\n    n_folds   = dplyr::n()\n  )\n\ncv_summary %>%\n  knitr::kable(\n    digits  = 2,\n    caption = \"Average MAE and RMSE across all districts (LOGO CV)\"\n  ) %>%\n  kableExtra::kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Average MAE and RMSE across all districts (LOGO CV)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> mean_MAE </th>\n   <th style=\"text-align:right;\"> mean_RMSE </th>\n   <th style=\"text-align:right;\"> n_folds </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 22.23 </td>\n   <td style=\"text-align:right;\"> 29.75 </td>\n   <td style=\"text-align:right;\"> 23 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## 5.3 Visualize error metrics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncv_by_district <- cv_results %>%\n  group_by(test_district) %>%\n  summarise(\n    mae  = mean(mae,  na.rm = TRUE),\n    rmse = mean(rmse, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\n# Merge with the police district base map\npolice_cv <- policeDistricts %>%\n  mutate(District = as.character(District)) %>%\n  left_join(cv_by_district, by = c(\"District\" = \"test_district\"))\n\n# RMSE spatial distribution\nggplot(police_cv) +\n  geom_sf(aes(fill = rmse)) +\n  labs(\n    title = \"LOGO CV RMSE by Police District\",\n    fill  = \"RMSE\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Assignment4_SpatialPredictiveAnalysis_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# MAE spatial distribution\nggplot(police_cv) +\n  geom_sf(aes(fill = mae)) +\n  labs(\n    title = \"LOGO CV MAE by Police District\",\n    fill  = \"MAE\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Assignment4_SpatialPredictiveAnalysis_files/figure-html/unnamed-chunk-25-2.png){width=672}\n:::\n:::\n\n\n-   Prediction errors **vary strongly** across the city.\n    -   Both RMSE and MAE maps show that some police districts have much higher prediction errors than others.\\\n    -   The lightest areas (middle and far-north districts) have RMSE \\> 60 and MAE \\> 50, meaning the model struggles most in these regions.\n-   **High-error** districts overlap with **low burglary** areas\n    -   The earlier burglary map showed that the northern parts of Chicago have very low burglary counts. These same areas now show the highest prediction errors.\n\n## 5.4 Chapter Summary\n\n-   **Leave-One-District-Out Cross-Validation**\n    -   The resaerch used **police districts** as spatial groups for cross-validation.\\\n    -   For each fold: Took one district as the test set, then used all the other districts as the training set. Fitted a Negative Binomial model with the same predictors as before: `mean_bldg_age`, `zone_code_dom`, `dist_to_hotspot`, and `knn_mean`. After that, Predicted burglary counts for the test district and calculated absolute error and squared error for each grid cell.\\\n    -   This process was repeated for **every police district**, so each district was left out once.\n-   **Error Metrics (MAE and RMSE)**\n    -   MAE (Mean Absolute Error): average size of errors.\\\n    -   RMSE (Root Mean Squared Error): penalizes large errors more strongly.\n-   **Mapping the Errors**\n    -   These maps show that prediction accuracy is **not uniform** across the city: Some districts (**especially in the north**) have higher MAE/RMSE, meaning the model struggles there. Districts in the **central and southern hotspot areas** tend to have lower errors, where burglary patterns are stronger and easier to learn.\n-   **Purpose of Step 5**\n    -   This step tests the model in a realistic spatial way: it predicts for entire **districts that were never seen in training**.\n    -   It reveals where the model is reliable and where it is weak, instead of only reporting a single global fit statistic.\n    -   The results show that the Negative Binomial model captures burglary patterns better in high-crime, hotspot districts, but has larger uncertainty in low-crime districts.\n\n# Step 6: Model Evaluation\n\n## 6.1 KDE baseline\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Extract XY coordinates of burglary points\nbur_xy <- st_coordinates(burglaries)\n\n# 2. Create a bounding window from the Chicago boundary\nwin_bbox <- spatstat.geom::owin(\n  xrange = st_bbox(chicagoBoundary)[c(\"xmin\", \"xmax\")],\n  yrange = st_bbox(chicagoBoundary)[c(\"ymin\", \"ymax\")]\n)\n\n# 3. Create a ppp object (point pattern) for burglaries\nbur_ppp <- spatstat.geom::ppp(\n  x      = bur_xy[, 1],\n  y      = bur_xy[, 2],\n  window = win_bbox\n)\n\n# 4. Kernel density estimate for the point pattern\n#    IMPORTANT: call density.ppp(bur_ppp, ...) — no \"X =\"\nbur_kde <- spatstat.explore::density.ppp(\n  bur_ppp,\n  sigma = 1000   # bandwidth in meters\n)\n\n# 5. Convert KDE to raster and extract values at grid centroids\nbur_kde_raster <- raster::raster(bur_kde)\nfishnet_centroids <- st_coordinates(st_centroid(fishnet))\n\nfishnet$kde_value <- raster::extract(\n  bur_kde_raster,\n  fishnet_centroids\n)\n\n# 6. Replace NA values (outside the KDE window) with 0\nfishnet$kde_value[is.na(fishnet$kde_value)] <- 0\n```\n:::\n\n\n## 6.2 Final model + predictions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the final NB model using all available training cells\nfinal_model <- glm.nb(\n  countBurglaries ~ mean_bldg_age + knn_mean + dist_to_hotspot + zone_prefix_dom,\n  data = fishnet_model\n)\n\n# Add NB predictions back to fishnet (matched by uniqueID)\nfishnet <- fishnet %>%\n  mutate(\n    prediction_nb = predict(\n      final_model,\n      newdata = fishnet_model,\n      type = \"response\"\n    )[match(uniqueID, fishnet_model$uniqueID)]\n  )\n\n# Normalize KDE predictions to total burglary count\nkde_sum   <- sum(fishnet$kde_value,       na.rm = TRUE)\ncount_sum <- sum(fishnet$countBurglaries, na.rm = TRUE)\n\nfishnet <- fishnet %>%\n  mutate(\n    prediction_kde = (kde_value / kde_sum) * count_sum\n  )\n\nfishnet <- fishnet %>%\n  mutate(\n    error_nb      = countBurglaries - prediction_nb,\n    abs_error_nb  = abs(error_nb),\n    error_kde     = countBurglaries - prediction_kde,\n    abs_error_kde = abs(error_kde)\n  )\n```\n:::\n\n\n## 6.3 Compare Actual vs NB vs KDE\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| fig-width: 12\n#| fig-height: 4\n\n# Actual counts\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  scale_fill_viridis_c(\n    name = \"Count\", option = \"plasma\", limits = c(0, 15)\n  ) +\n  labs(title = \"Actual Burglaries (2017)\") +\n  theme_default()\n\n# Negative Binomial predictions\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_nb), color = NA) +\n  scale_fill_viridis_c(\n    name = \"Predicted\", option = \"plasma\", limits = c(0, 15)\n  ) +\n  labs(title = \"NB Model Predictions\") +\n  theme_default()\n\n# KDE baseline predictions\np3 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_kde), color = NA) +\n  scale_fill_viridis_c(\n    name = \"Predicted\", option = \"plasma\", limits = c(0, 15)\n  ) +\n  labs(title = \"KDE Baseline Predictions\") +\n  theme_default()\n\n# Combine the three maps\np1 + p2 + p3 +\n  plot_annotation(\n    title = \"Actual vs Predicted Burglaries\",\n    subtitle = \"Comparing NB Model and KDE Baseline\"\n  )\n```\n\n::: {.cell-output-display}\n![](Assignment4_SpatialPredictiveAnalysis_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n-   All three maps show the same broad structure: higher burglary levels in the **middle north and middle south** parts of Chicago, and much lower activity in the **middle, far north and far south** part of the city.\n-   The actual burglary map shows sharp, uneven hotspots. The NB model captures the broad hotspot regions and major regional contrasts, but **produces smoother predictions** because it relies on **explanatory variables** such as building age, zoning, and hotspot distance.\\\n-   The KDE baseline looks visually similar to the actual map, but this is expected, as KDE **simply smooths the observed data** without any modeling of underlying urban processes.\n\n## 6.4 Model performance comparison (MAE / RMSE)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate MAE and RMSE for NB model and KDE baseline\ncomparison <- fishnet %>%\n  st_drop_geometry() %>%\n  filter(!is.na(prediction_nb), !is.na(prediction_kde)) %>%\n  summarize(\n    model_mae  = mean(abs(countBurglaries - prediction_nb)),\n    model_rmse = sqrt(mean((countBurglaries - prediction_nb)^2)),\n    kde_mae    = mean(abs(countBurglaries - prediction_kde)),\n    kde_rmse   = sqrt(mean((countBurglaries - prediction_kde)^2))\n  )\n\n# Reshape and print the table\ncomparison %>%\n  pivot_longer(\n    everything(), names_to = \"metric\", values_to = \"value\"\n  ) %>%\n  separate(metric, into = c(\"approach\", \"metric\"), sep = \"_\") %>%\n  pivot_wider(names_from = metric, values_from = value) %>%\n  kable(\n    digits = 2,\n    caption = \"Model Performance: NB vs KDE\"\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Model Performance: NB vs KDE</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> approach </th>\n   <th style=\"text-align:right;\"> mae </th>\n   <th style=\"text-align:right;\"> rmse </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> model </td>\n   <td style=\"text-align:right;\"> 2.5 </td>\n   <td style=\"text-align:right;\"> 3.52 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> kde </td>\n   <td style=\"text-align:right;\"> 2.1 </td>\n   <td style=\"text-align:right;\"> 2.98 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n-   KDE achieves lower MAE and RMSE because it **directly smooths the observed burglary events**, essentially reproducing the spatial pattern of the actual data. This makes KDE a **strong spatial baseline** but not a predictive or explanatory model.\\\n-   In contrast, the Negative Binomial model aims to **explain burglary variation using built-environment and zoning characteristics**, rather than simply interpolating past events. Therefore, its higher error values are expected and do not indicate model failure. Instead, the NB model provides interpretability and generalization ability that KDE cannot offer.\n\n## 6.5 Spatial Distribution of Prediction Errors\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Signed error (NB)\np_nb_err <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = error_nb), color = NA) +\n  scale_fill_gradient2(\n    name     = \"Error\",\n    low      = \"#2166ac\",\n    mid      = \"white\",\n    high     = \"#b2182b\",\n    midpoint = 0,\n    limits   = c(-10, 10)\n  ) +\n  labs(title = \"NB Model: Signed Error\") +\n  theme_default()\n\n# Absolute error (NB)\np_nb_abs <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = abs_error_nb), color = NA) +\n  scale_fill_viridis_c(\n    name   = \"Abs. Error\",\n    option = \"magma\"\n  ) +\n  labs(title = \"NB Model: Absolute Error\") +\n  theme_default()\n\n# Signed error (KDE)\np_kde_err <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = error_kde), color = NA) +\n  scale_fill_gradient2(\n    name     = \"Error\",\n    low      = \"#2166ac\",\n    mid      = \"white\",\n    high     = \"#b2182b\",\n    midpoint = 0,\n    limits   = c(-10, 10)\n  ) +\n  labs(title = \"KDE Baseline: Signed Error\") +\n  theme_default()\n\n# Absolute error (KDE)\np_kde_abs <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = abs_error_kde), color = NA) +\n  scale_fill_viridis_c(\n    name   = \"Abs. Error\",\n    option = \"magma\"\n  ) +\n  labs(title = \"KDE Baseline: Absolute Error\") +\n  theme_default()\n\n# Combine 4 plots in 2×2 layout\n(p_nb_err + p_nb_abs) /\n(p_kde_err + p_kde_abs)\n```\n\n::: {.cell-output-display}\n![](Assignment4_SpatialPredictiveAnalysis_files/figure-html/unnamed-chunk-30-1.png){width=1152}\n:::\n:::\n\n\n-   **NB Model: Signed Error(Top-Left)**\n    -   Under-prediction happens more in major hotspot regions (especially central–south), while over-prediction appears more in low-crime northern areas.\\\n    -   This reflects the NB model's reliance on **built-environment variables**, which smooth the predictions and do not fully capture local spikes.\n-   **NB Model: Absolute Error(Top-Right)**\n    -   Absolute errors are larger mainly in districts with very high or very low burglary counts.\\\n    -   High-crime areas in the south show moderate errors but not extreme ones.\\\n    -   The NB model handles high-crime zones better because built-environment variables explain these areas more consistently.\n-   **KDE Baseline: Signed Error(Bottom-Left)**\n    -   KDE errors are much more random and noisy.\\\n    -   The spatial error pattern lacks structure; KDE simply smooths nearby crime counts.\\\n    -   This randomness reflects that **KDE is not a model**. It only uses spatial proximity and does not incorporate zoning or urban characteristics.\n-   **KDE Baseline: Absolute Error(Bottom-Right)**\n    -   Absolute errors are generally smaller than NB (expected), because KDE is effectively a **smoothed version of the real data**.\n-   NB shows more structured errors because it predicts using **explanatory variables**. This is not a failure, it's evidence that the **NB model is capturing urban mechanisms**, not just smoothing past data.\n\n## 6.6 Chapter Summary\n\n-   **KDE Baseline:**\n    -   This chapter built a KDE (Kernel Density Estimation) surface using the burglary point pattern.\\\n    -   KDE acts as a **spatial baseline**: it uses only the locations of past events, without any built-environment variables.\n-   **Final NB Model and Predictions:**\n    -   In this chapter, I fitted a final Negative Binomial model using all training cells from `fishnet_model`, including `mean_bldg_age`, `knn_mean`, `dist_to_hotspot`, `zone_prefix_dom`.\\\n    -   Research generated NB predictions for each grid cell and stored them as `prediction_nb`. Meanwhile, this chapter used the KDE values to create a KDE prediction `prediction_kde` for each cell.\\\n    -   For both approaches, compute signed error and absolute error relative to the actual burglary counts.\n-   **Overall Interpretation of Step 6:**\n    -   Step 6 evaluates whether the Negative Binomial model provides reasonable and useful predictions compared to a strong spatial baseline (KDE).\\\n    -   Results show that:\n        -   KDE achieves slightly lower MAE/RMSE because it effectively reproduces the observed pattern by smoothing the data.\\\n        -   The NB model offers **interpretable, mechanism-based predictions**, linking burglary risk to building age, zoning, rodent baiting requests hotspot distance, and its neighborhood feature, even though its errors are somewhat higher.\\\n    -   Therefore, KDE is useful as a **benchmark for spatial clustering**, while the NB model is more valuable for understanding and explaining where and why burglaries concentrate, and for generalizing to new times or scenarios.\n\n# Step7: Summary Statistics and Tables\n\n## 7.1 Model Summary Table\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Lookup full zoning labels\nzoning_labels <- c(\n  \"RS\"  = \"Residential Single-Unit District\",\n  \"RT\"  = \"Residential Two-Flat, Townhouse and Multi-Unit District\",\n  \"RM\"  = \"Residential Multi-Unit District\",\n  \"B\"   = \"Business\",\n  \"C\"   = \"Commercial\",\n  \"DC\"  = \"Downtown Core District\",\n  \"DR\"  = \"Downtown Residential District\",\n  \"DS\"  = \"Downtown Service District\",\n  \"DX\"  = \"Downtown Mixed-Use District\",\n  \"M\"   = \"Manufacturing\",\n  \"PMD\" = \"Planned Manufacturing Districts\",\n  \"PD\"  = \"Planned Development\",\n  \"T\"   = \"Transportation\",\n  \"POS\" = \"Parks and Open Space\"\n)\n\nmodel_summary <- broom::tidy(final_model, exponentiate = TRUE) %>%\n  mutate(\n    term = dplyr::case_when(\n      term == \"(Intercept)\"      ~ \"Intercept\",\n      term == \"mean_bldg_age\"    ~ \"Mean building age\",\n      term == \"knn_mean\"         ~ \"KNN mean (neighboring rodent baiting requests)\",\n      term == \"dist_to_hotspot\"  ~ \"Distance to rodent hotspot\",\n\n      # Zoning coefficients: zone_prefix_domRS, zone_prefix_domRT\n      \n      grepl(\"^zone_prefix_dom\", term) ~ paste0(\n        \"Zoning: \",\n        sub(\"zone_prefix_dom\", \"\", term), \n        \" (\",\n        zoning_labels[sub(\"zone_prefix_dom\", \"\", term)],\n        \")\"\n      ),\n\n      TRUE ~ term\n    ),\n    # Round all numeric columns\n    dplyr::across(where(is.numeric), ~round(.x, 3))\n  )\n\nmodel_summary %>%\n  kable(\n    caption   = \"Final Negative Binomial Model Coefficients (Exponentiated Rate Ratios)\",\n    col.names = c(\"Variable\", \"Rate Ratio\", \"Std. Error\", \"Z\", \"P-Value\")\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\")) %>%\n  footnote(\n    general = paste(\n      \"Rate ratios > 1 indicate a positive association with burglary counts,\",\n      \"while rate ratios < 1 indicate a negative association.\",\n      \"Zoning (land use) is a categorical variable; each zoning category is interpreted\",\n      \"relative to the reference category (the omitted baseline level of zone_prefix_dom).\"\n    )\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;border-bottom: 0;\">\n<caption>Final Negative Binomial Model Coefficients (Exponentiated Rate Ratios)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> Rate Ratio </th>\n   <th style=\"text-align:right;\"> Std. Error </th>\n   <th style=\"text-align:right;\"> Z </th>\n   <th style=\"text-align:right;\"> P-Value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Intercept </td>\n   <td style=\"text-align:right;\"> 0.714 </td>\n   <td style=\"text-align:right;\"> 0.126 </td>\n   <td style=\"text-align:right;\"> -2.667 </td>\n   <td style=\"text-align:right;\"> 0.008 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Mean building age </td>\n   <td style=\"text-align:right;\"> 1.020 </td>\n   <td style=\"text-align:right;\"> 0.001 </td>\n   <td style=\"text-align:right;\"> 16.204 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> KNN mean (neighboring rodent baiting requests) </td>\n   <td style=\"text-align:right;\"> 1.003 </td>\n   <td style=\"text-align:right;\"> 0.002 </td>\n   <td style=\"text-align:right;\"> 1.613 </td>\n   <td style=\"text-align:right;\"> 0.107 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Distance to rodent hotspot </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -1.137 </td>\n   <td style=\"text-align:right;\"> 0.256 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Zoning: C (Commercial) </td>\n   <td style=\"text-align:right;\"> 0.896 </td>\n   <td style=\"text-align:right;\"> 0.089 </td>\n   <td style=\"text-align:right;\"> -1.239 </td>\n   <td style=\"text-align:right;\"> 0.216 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Zoning: DR (Downtown Residential District) </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 114839.703 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Zoning: DS (Downtown Service District) </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 80757.872 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Zoning: DX (Downtown Mixed-Use District) </td>\n   <td style=\"text-align:right;\"> 1.391 </td>\n   <td style=\"text-align:right;\"> 0.359 </td>\n   <td style=\"text-align:right;\"> 0.921 </td>\n   <td style=\"text-align:right;\"> 0.357 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Zoning: M (Manufacturing) </td>\n   <td style=\"text-align:right;\"> 0.463 </td>\n   <td style=\"text-align:right;\"> 0.098 </td>\n   <td style=\"text-align:right;\"> -7.891 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Zoning: PD (Planned Development) </td>\n   <td style=\"text-align:right;\"> 0.800 </td>\n   <td style=\"text-align:right;\"> 0.092 </td>\n   <td style=\"text-align:right;\"> -2.432 </td>\n   <td style=\"text-align:right;\"> 0.015 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Zoning: PMD (Planned Manufacturing Districts) </td>\n   <td style=\"text-align:right;\"> 0.440 </td>\n   <td style=\"text-align:right;\"> 0.194 </td>\n   <td style=\"text-align:right;\"> -4.233 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Zoning: POS (Parks and Open Space) </td>\n   <td style=\"text-align:right;\"> 0.771 </td>\n   <td style=\"text-align:right;\"> 0.156 </td>\n   <td style=\"text-align:right;\"> -1.661 </td>\n   <td style=\"text-align:right;\"> 0.097 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Zoning: RM (Residential Multi-Unit District) </td>\n   <td style=\"text-align:right;\"> 1.107 </td>\n   <td style=\"text-align:right;\"> 0.112 </td>\n   <td style=\"text-align:right;\"> 0.908 </td>\n   <td style=\"text-align:right;\"> 0.364 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Zoning: RS (Residential Single-Unit District) </td>\n   <td style=\"text-align:right;\"> 0.865 </td>\n   <td style=\"text-align:right;\"> 0.058 </td>\n   <td style=\"text-align:right;\"> -2.478 </td>\n   <td style=\"text-align:right;\"> 0.013 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Zoning: RT (Residential Two-Flat, Townhouse and Multi-Unit District) </td>\n   <td style=\"text-align:right;\"> 0.969 </td>\n   <td style=\"text-align:right;\"> 0.081 </td>\n   <td style=\"text-align:right;\"> -0.393 </td>\n   <td style=\"text-align:right;\"> 0.694 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Zoning: T (Transportation) </td>\n   <td style=\"text-align:right;\"> 0.587 </td>\n   <td style=\"text-align:right;\"> 0.755 </td>\n   <td style=\"text-align:right;\"> -0.706 </td>\n   <td style=\"text-align:right;\"> 0.480 </td>\n  </tr>\n</tbody>\n<tfoot>\n<tr><td style=\"padding: 0; \" colspan=\"100%\"><span style=\"font-style: italic;\">Note: </span></td></tr>\n<tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Rate ratios &gt; 1 indicate a positive association with burglary counts, while rate ratios &lt; 1 indicate a negative association. Zoning (land use) is a categorical variable; each zoning category is interpreted relative to the reference category (the omitted baseline level of zone_prefix_dom).</td></tr>\n</tfoot>\n</table>\n\n`````\n:::\n:::\n\n\n-   **Mean building age** has a strong and significant positive effect. For each extra year of average building age in a grid cell, the expected burglary count increases by about 2%, holding other variables constant.\n\n-   **Manufacturing (M) and Planned Manufacturing Districts (PMD)** both have p \\< 0.001, and their Rate Ratio both lower than 1, meaning that burglary risk in industrial zones is much lower than in the reference zoning category.\n\n-   **Planned development areas(PD)**(RR ≈ 0.80, p ≈ 0.015) also show lower burglary risk.\n\n-   **Residential Single-Unit (RS)**(RR ≈ 0.87, p ≈ 0.013) have somewhat lower burglary counts than the reference zoning.\n\n-   Some downtown categories (DR, DS) have extreme rate ratios and huge standard errors, likely because there are very few grid cells of these types, so their coefficients should be interpreted with caution.\n\n## 7.2 Discussion and Limitations\n\nThis study shows that the NB model can capture some broad burglary patterns, such as higher risk in areas with older buildings and lower risk in manufacturing zones. However, the model also has clear limitations. Some of the variables I included—such as rodent KNN and distance to rodent hotspots—were chosen somewhat loosely and do not strongly relate to burglary in the results. Because of this, the model cannot explain the sharp hotspots seen in the actual data. Overall, while the NB model offers some useful insights, its performance is restricted by both the choice of variables and the model structure, and future work should include more relevant predictors and more advanced spatial methods.\n",
    "supporting": [
      "Assignment4_SpatialPredictiveAnalysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}